### PR TITLE
Make local connections use AF_INET6, too

### LINKED ISSUE #4: Connection to localhost or local IPs fails
Going to have to open another bug report: When trying to connect to localhost (127.0.0.1) or a host in my local network, that doesn't work. 

Test case: `TNAT64_DEBUG=10 LD_PRELOAD=/tmp/libtnat64.so strace telnet 127.0.0.1 22` (so, just a random telnet connection to port 22). When I do that for a public IP, everything works. When I do that for 127.0.0.1 or an IP that's in my local network, the debug log prints "Connection for socket X is local", then tries to call `realconnect` - but for some reason, that returns -1 for me. 

I haven't yet been able to figure out why that happens, maybe you have an idea? 

Here's the full log: 
```
$ TNAT64_DEBUG=10 LD_PRELOAD=/tmp/libtnat64.so telnet 127.0.0.1 22
Trying 127.0.0.1...
19:27:48 libtnat64(222188): Got connection request
19:27:48 libtnat64(222188): Opening configuration file (/etc/tnat64.conf)
19:27:48 libtnat64(222188): New network entry for 10.0.0.0 going to 0xf2186020
19:27:48 libtnat64(222188): New network entry for 127.0.0.0 going to 0xf2186070
19:27:48 libtnat64(222188): Got connection request for socket 3 to 127.0.0.1:22
19:27:48 libtnat64(222188): Connection for socket 3 is local
telnet: Unable to connect to remote host: Invalid argument
```

I believe the issue is that `telnet 127.0.0.1 22` without your library will open an AF_INET socket: `socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3`

Running telnet with your library, it creates an AF_INET6 socket instead due to the rewrite in `socket` in tnat64.c - as it should be, so that it can connect to IPv6 destinations:
`socket(AF_INET6, SOCK_STREAM, IPPROTO_IP) = 3`
and then, it tries to use that AF_INET6 socket to connect to an AF_INET destination:
`connect(3, {sa_family=AF_INET, sin_port=htons(22), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINVAL`
and that obviously fails because you can't do AF_INET connections on an AF_INET6 socket. 

What I'm assuming needs to happen in this case is that instead of giving "AF_INET" and an IPv4 to the realconnect call, you'd need to put AF_INET6 and the corresponding IPv4-mapped address into the connect call - so in my case, that'd be `::ffff:7f00:0001` or `::ffff:127.0.0.1` instead of `127.0.0.1`. Also, the socket option "IPV6_V6ONLY" needs to be set to 0/False. That's usually the default value in most OSes, but not in all of them.

Let me know if I'm misunderstanding something or if I'm making a mistake, but that seems to be a bug in the library.

### PR DESCRIPTION
**Pull request by Leseratte10**
As mentioned in issue #4, when I try to perform a TCP connection to localhost, this fails because an IPv6 AF_INET6 socket (as created by tnat64) can't connect to an AF_INET IPv4 destination. 

This is fixed by: 

- setting the socket option `IPV6_V6ONLY` to false after creating an IPv6 socket - this is the default on most systems but not on all, and it makes sure that this IPv6 socket allows to connect to IPv4 destinations, too; and
- by adding the IPv4-mapped prefix `::ffff:` in front of the IPv4 address destination for local destinations so that an IPv6 socket can accept it. 

With this PR, `LD_PRELOAD=libtnat64.so telnet 127.0.0.1 22` works while it previously failed.

### CODE REVIEW

File: tnat64.c [hunk 1]
```diff
@@ -175,7 +175,19 @@ int socket(SOCKET_SIGNATURE)
     }
     if ((__domain == AF_INET) && ((__type & SOCK_TYPE_MASK) == SOCK_STREAM))
     {
-        return realsocket(AF_INET6, __type, __protocol);
+        int retval = realsocket(AF_INET6, __type, __protocol);
+
+        if (retval >= 0) {
```
Comment (andrewshadura) [inline tnat64.c]: How about `if (ret < 0) { return ret; }` same as elsewhere?

**Comment by andrewshadura** [comment]
Thanks! Please see the comment above.

File: tnat64.c (hunk 1 above)
Comment (Leseratte10) [reply tnat64.c]: Done.

File: tnat64.c [hunk 2]
```diff
@@ -175,7 +175,21 @@ int socket(SOCKET_SIGNATURE)
     }
     if ((__domain == AF_INET) && ((__type & SOCK_TYPE_MASK) == SOCK_STREAM))
     {
-        return realsocket(AF_INET6, __type, __protocol);
+        int retval = realsocket(AF_INET6, __type, __protocol);
+
+        if (retval < 0) {
+            return retval;
+        }
```
Comment (andrewshadura) [inline tnat64.c]:
```suggestion
        int sock = realsocket(AF_INET6, __type, __protocol);

        if (sock < 0) {
            return sock;
        }
```

File: tnat64.c [hunk 3]
```diff
@@ -175,7 +175,21 @@ int socket(SOCKET_SIGNATURE)
...
+
+        // Now set this IPv6 socket to allow both IPv6 and IPv4 connections. 
+        // Most OSes do that by default, but not all. 
+        int no = 0;
+        int setsockopt_retval = setsockopt(retval, IPPROTO_IPV6, IPV6_V6ONLY, (void*)&no, sizeof(no));
+        if (setsockopt_retval != 0) {
+            show_msg(MSGDEBUG, "Failed to disable IPV6_V6ONLY for socket %d: error %d\n", retval, setsockopt_retval);
+        }
```
Comment (andrewshadura) [inline tnat64.c]:
```suggestion
        if (setsockopt(sock, IPPROTO_IPV6, IPV6_V6ONLY, (void*)&no, sizeof(no)) < 0) {
            show_msg(MSGDEBUG, "Failed to disable IPV6_V6ONLY for socket %d: error %d (%s)\n", sock, errno, strerror(errno));
        }
```

File: tnat64.c [hunk 4]
```diff
@@ -175,7 +175,21 @@ int socket(SOCKET_SIGNATURE)
...
+
+        return retval;
```
Comment (andrewshadura) [inline tnat64.c]:
```suggestion
        return sock;
```

**Review by andrewshadura — CHANGES_REQUESTED** [review]

**Comment by andrewshadura** [comment]
@Leseratte10, how about this? 🙂 ↑

**Comment by Leseratte10** [comment]
Yeah that's probably a bit cleaner. But I'd suggest squashing the three fixup commits into one (or into the first commit that adds the feature).

**Comment by andrewshadura** [comment]
Yes, `git rebase -i --autosq` will do just that if you run it.

**Review by andrewshadura — APPROVED** [review]

**Review by andrewshadura — CHANGES_REQUESTED** [review]
I think your rebasing didn’t go well 🙂

**Comment by Leseratte10** [comment]
Yeah, just noticed that, trying to fix it :P

**Comment by andrewshadura** [comment]
Right, it was my fault: I used the wrong commit’s message.

**Comment by Leseratte10** [comment]
Okay now it should be correct, hopefully.

**Review by andrewshadura — APPROVED** [review]
